export interface NewsItem {
    id: string;
    category: string;
    sourceType: '코스모스' | '생성형';
    title: string;
    summary: string;
    date: string;
    source: string;
    publishDate: string;
    imageUrl: string;
    body: string[];
    originalUrl?: string;
    location?: {
        name: string;
        lat: number;
        lng: number;
    };
}

export const NEWS_DATA: NewsItem[] = [
    {
        id: '1',
        sourceType: '생성형',
        category: '탐사',
        title: '고요의 바다 남쪽 구역에서 희토류 매장 가능성 확인',
        summary: '최근 루나 게이트웨이(Lunar Gateway)의 고해상도 분광계 분석 결과, 달의 고요의 바다 남부에서 이례적인 밀도의 희토류 원소 신호가 포착되었습니다.',
        date: '2시간 전',
        source: 'Lunar Times',
        publishDate: '2024. 05. 24',
        imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1080&auto=format&fit=crop',
        body: [
            '최근 루나 게이트웨이(Lunar Gateway)의 고해상도 분광계 분석 결과, 달의 북위 14.5도, 동경 20.3도 부근의 지표면 아래에서 이례적인 밀도의 희토류 원소 신호가 포착되었습니다. 이는 향후 달 기지 건설 및 자원 확보 경쟁에서 매우 중요한 전환점이 될 것으로 보입니다.',
            '이번에 발견된 매장지는 과거 아폴로 11호의 착륙 지점에서 그리 멀지 않은 곳으로, 초기 탐사 결과에 따르면 지표면 2미터 이내의 비교적 얕은 곳에 위치한 것으로 추정됩니다. 루나 탐사 연합(LEA)은 해당 구역을 \'골든 호라이즌\'으로 명명하고 상세 탐사 계획을 수립 중입니다.',
            '전문가들은 이번 발견이 단순한 자원 확보를 넘어, 달 영유권 주장 및 토지 소유권 가치에 지대한 영향을 미칠 것으로 내다보고 있습니다. 현재 해당 좌표 주변의 점유권 거래량은 평소 대비 400% 이상 급증한 상태입니다.',
        ],
        location: {
            name: '고요의 바다 남부 (골든 호라이즌)',
            lat: 14.5,
            lng: 20.3,
        },
    },
    {
        id: '2',
        sourceType: '생성형',
        category: '기술',
        title: '제3세대 월면 거주 모듈 테스트 성공적 마무리',
        summary: '월면토(Regolith)를 활용한 자율 주행 3D 프린팅 로봇의 지상 시연이 성공적으로 마무리되었습니다.',
        date: '5시간 전',
        source: 'Space Tech Weekly',
        publishDate: '2024. 05. 23',
        imageUrl: 'https://images.unsplash.com/photo-1541873676-a18131494184?q=80&w=1080&auto=format&fit=crop',
        body: [
            '현대건설과 한국항공우주연구원이 공동 개발한 제3세대 월면 거주 모듈이 6개월간의 혹한/진공 시뮬레이션 테스트를 성공적으로 통과했습니다.',
            '이번 모듈은 월면토(Regolith)를 원료로 사용하는 3D 프린팅 로봇이 자율적으로 건축하는 방식으로, 기존 대비 건설 시간을 70% 단축하고 내구성을 3배 향상시켰습니다.',
            '특히 방사선 차폐 성능이 크게 개선되어, 실제 달 환경에서 최대 4명의 우주인이 6개월 이상 거주할 수 있을 것으로 기대됩니다. 2027년 첫 실제 달 표면 건설이 계획되어 있습니다.',
        ],
    },
    {
        id: '3',
        sourceType: '생성형',
        category: '자원',
        title: '민간 기업의 달 광물 채굴권 입찰 가이드라인 발표',
        summary: '폭풍의 대양 북부 섹터의 헬륨-3 채굴권이 어제 마감된 우주 자원 경매에서 사상 최고가를 기록하며 낙찰되었습니다.',
        date: '어제',
        source: 'Moon Economy',
        publishDate: '2024. 05. 22',
        imageUrl: 'https://images.unsplash.com/photo-1506443432602-ac2fcd6f54e0?q=80&w=1080&auto=format&fit=crop',
        body: [
            '국제 우주 자원 관리국(ISRMA)이 민간 기업의 달 광물 채굴권 입찰에 대한 공식 가이드라인을 발표했습니다. 이번 가이드라인은 폭풍의 대양(Oceanus Procellarum) 북부 섹터를 중심으로 적용됩니다.',
            '채굴권은 10km² 단위로 분할되며, 최소 입찰가는 구역당 500만 달러로 책정되었습니다. 헬륨-3 매장량이 확인된 구역은 프리미엄이 붙어 최대 5,000만 달러까지 치솟을 것으로 예상됩니다.',
            '업계에서는 이번 가이드라인이 달 자원 경제의 본격적인 시작을 알리는 신호탄으로 평가하고 있습니다.',
        ],
        location: {
            name: '폭풍의 대양 북부',
            lat: 18.2,
            lng: -54.3,
        },
    },
    {
        id: '4',
        sourceType: '생성형',
        category: '탐사',
        title: '달 뒷면 심우주 관측소 건설 계획',
        summary: '국제 공동 연구팀이 달 뒷면에 심우주 관측소를 건설하는 계획을 발표했습니다.',
        date: '어제',
        source: 'Deep Space Journal',
        publishDate: '2024. 05. 21',
        imageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?q=80&w=1080&auto=format&fit=crop',
        body: [
            '유럽우주국(ESA)과 중국국가항천국(CNSA)이 달 뒷면 남위 45도, 서경 170도 지점에 심우주 전파 관측소를 건설하는 공동 프로젝트를 발표했습니다.',
            '달 뒷면은 지구의 전파 간섭이 없어 심우주 관측에 최적의 환경을 제공합니다. 이 관측소는 빅뱅 직후의 우주 신호를 탐지하는 것을 목표로 합니다.',
            '건설은 2028년 시작될 예정이며, 완공 후에는 인류 역사상 가장 민감한 전파 망원경이 될 것입니다.',
        ],
        location: {
            name: '달 뒷면 남부',
            lat: -45.0,
            lng: -170.0,
        },
    },
    {
        id: '5',
        sourceType: '생성형',
        category: '분석',
        title: '2026년 달 경제 시장 전망 보고서',
        summary: '달 기반 경제 생태계의 성장세를 분석하고 향후 5년간의 시장 규모와 투자 전망을 다룹니다.',
        date: '2일 전',
        source: 'Cosmos Analytics',
        publishDate: '2024. 05. 20',
        imageUrl: 'https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?q=80&w=1080&auto=format&fit=crop',
        body: [
            '글로벌 투자은행 모건스탠리의 최신 보고서에 따르면, 달 경제 시장 규모는 2030년까지 연간 1조 달러를 돌파할 것으로 전망됩니다.',
            '주요 성장 동력은 헬륨-3 에너지, 희토류 채굴, 우주 관광, 그리고 달 토지 점유권 거래입니다. 특히 토지 점유권 시장은 연평균 280% 성장률을 기록하고 있습니다.',
            '보고서는 달 경제가 초기 투기적 단계에서 실물 경제 기반의 산업 단계로 전환되고 있다고 분석했습니다. 다만 국제법적 불확실성이 여전히 리스크 요인으로 남아있다고 경고했습니다.',
        ],
    },
    {
        id: '6',
        sourceType: '생성형',
        category: '자원',
        title: '헬륨-3 추출 효율 30% 향상 기술 특허 출원',
        summary: '한국원자력연구원이 월면토에서 헬륨-3를 기존 대비 30% 효율적으로 추출하는 신기술을 개발, 국제 특허를 출원했습니다.',
        date: '3일 전',
        source: 'Korea Science Daily',
        publishDate: '2024. 05. 19',
        imageUrl: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?q=80&w=1080&auto=format&fit=crop',
        body: [
            '한국원자력연구원이 마이크로웨이브 가열 방식을 활용한 새로운 헬륨-3 추출 기술을 개발, 국제 특허를 출원했습니다. 기존 기술 대비 추출 효율이 30% 향상되었습니다.',
            '이 기술은 월면토를 800도까지 가열하는 기존 방식 대신, 마이크로웨이브로 선택적으로 가열하여 에너지 소모를 절반으로 줄이면서도 수율을 높이는 방식입니다.',
            '상용화 시 달 현지에서의 핵융합 연료 생산 비용을 획기적으로 낮출 수 있어, 달 에너지 자립의 핵심 기술로 주목받고 있습니다.',
        ],
    },
    {
        id: '7',
        sourceType: '생성형',
        category: '탐사',
        title: 'Perseverance 로버, 화성 토양에서 유기 화합물 발견',
        summary: 'NASA의 Perseverance 로버가 예제로 분화구 내 퇴적층에서 복잡한 유기 화합물을 감지했습니다.',
        date: '3일 전',
        source: 'NASA JPL',
        publishDate: '2024. 05. 19',
        imageUrl: 'https://images.unsplash.com/photo-1614728263952-84ea256f9679?q=80&w=1080&auto=format&fit=crop',
        body: [
            'NASA의 Perseverance 로버가 예제로 분화구 퇴적층에서 복잡한 유기 화합물을 감지했습니다. 이 발견은 화성에 과거 미생물이 존재했을 가능성을 높이는 중요한 단서입니다.',
            'SHERLOC 분광기를 통해 확인된 이 화합물은 아미노산과 유사한 구조를 가지고 있으며, 추가 분석이 진행 중입니다.',
        ],
    },
    {
        id: '8',
        sourceType: '생성형',
        category: '기술',
        title: 'SpaceX Starship, 달 착륙선 변형 모델 공개',
        summary: 'SpaceX가 NASA의 아르테미스 프로그램에 사용될 Starship 달 착륙선의 최종 디자인을 공개했습니다.',
        date: '4일 전',
        source: 'SpaceX News',
        publishDate: '2024. 05. 18',
        imageUrl: 'https://images.unsplash.com/photo-1517976487492-5750f3195933?q=80&w=1080&auto=format&fit=crop',
        body: [
            'SpaceX가 NASA 아르테미스 프로그램용 Starship HLS(Human Landing System)의 최종 디자인을 공개했습니다.',
            '기존 Starship 대비 착륙 다리가 확장되었으며, 선외 활동을 위한 에어록과 엘리베이터 시스템이 추가되었습니다.',
        ],
    },
    {
        id: '9',
        sourceType: '생성형',
        category: '자원',
        title: '남극 영구음영지역 얼음 매장량, 예상보다 3배 많아',
        summary: '달 정찰 궤도선(LRO)의 최신 관측 데이터 분석에 따르면 남극 영구음영지역의 수빙 매장량이 기존 추정의 3배에 달합니다.',
        date: '5일 전',
        source: 'Lunar Research Institute',
        publishDate: '2024. 05. 17',
        imageUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=1080&auto=format&fit=crop',
        body: [
            '달 정찰 궤도선(LRO)의 중성자 분광계 최신 데이터에 따르면, 남극 영구음영지역의 수빙 매장량이 약 6억 톤으로 기존 추정(2억 톤)의 3배에 달하는 것으로 나타났습니다.',
            '이 물은 로켓 추진제, 생활용수, 산소 생산에 활용될 수 있어 달 기지 건설의 핵심 자원입니다.',
        ],
        location: {
            name: '달 남극 영구음영지역',
            lat: -89.9,
            lng: 0,
        },
    },
    {
        id: '10',
        sourceType: '생성형',
        category: '분석',
        title: '달 토지 점유권 거래량 역대 최고치 경신',
        summary: '2026년 1분기 달 토지 점유권 거래량이 전 분기 대비 180% 증가하며 역대 최고치를 경신했습니다.',
        date: '6일 전',
        source: 'Moon Market Watch',
        publishDate: '2024. 05. 16',
        imageUrl: 'https://images.unsplash.com/photo-1504192010706-dd7f569ee2be?q=80&w=1080&auto=format&fit=crop',
        body: [
            '달 토지 점유권 시장이 폭발적 성장세를 이어가고 있습니다. 2026년 1분기 거래량은 12만 건으로, 전 분기 대비 180% 급증했습니다.',
            '특히 고요의 바다와 풍요의 바다 인근 구역이 가장 활발한 거래를 보이고 있으며, 평균 거래가도 40% 상승했습니다.',
        ],
    },
    {
        id: '11',
        sourceType: '생성형',
        category: '기술',
        title: 'JAXA, 달 표면 양자 통신 실험 성공',
        summary: '일본 우주항공연구개발기구(JAXA)가 달-지구 간 양자 암호 통신에 세계 최초로 성공했습니다.',
        date: '1주일 전',
        source: 'JAXA Press',
        publishDate: '2024. 05. 15',
        imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=1080&auto=format&fit=crop',
        body: [
            'JAXA가 달 궤도선에서 지구로 양자 암호화된 데이터를 전송하는 데 성공했습니다. 이는 38만km 거리에서의 양자 통신으로 세계 최초입니다.',
            '이 기술은 향후 달 기지와 지구 간 해킹 불가능한 보안 통신을 가능케 할 핵심 기반 기술입니다.',
        ],
    },
    {
        id: '12',
        sourceType: '생성형',
        category: '탐사',
        title: 'James Webb, 천왕성의 29번째 위성 발견',
        summary: 'James Webb 우주 망원경이 천왕성 주변에서 이전에 발견되지 않은 소형 위성을 발견했습니다.',
        date: '1주일 전',
        source: 'ESA Bulletin',
        publishDate: '2024. 05. 14',
        imageUrl: 'https://images.unsplash.com/photo-1462332420958-a05d1e002413?q=80&w=1080&auto=format&fit=crop',
        body: [
            'James Webb 우주 망원경이 천왕성 주변을 관측하던 중 직경 약 8km의 소형 위성을 발견했습니다.',
            '이 위성은 천왕성의 29번째 위성으로, 불규칙 궤도를 가진 포획 천체로 추정됩니다. 발견 이후 국제천문연맹(IAU)에 공식 등록 절차가 진행 중입니다.',
        ],
    },
];

export const MY_LANDS = [
    {
        id: 'L-2024-001',
        location: 'Mare Tranquillitatis (고요의 바다)',
        coordinates: 'Lat 0.67N, Lon 23.47E',
        area: '100',
        purchaseDate: '2025.12.15',
        imageUrl: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?q=80&w=1080&auto=format&fit=crop',
    },
    {
        id: 'L-2025-042',
        location: 'Oceanus Procellarum (폭풍의 대양)',
        coordinates: 'Lat 18.2N, Lon 54.3W',
        area: '50',
        purchaseDate: '2026.01.10',
        imageUrl: 'https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?q=80&w=1080&auto=format&fit=crop',
    },
];

export const SCRAPPED_NEWS: NewsItem[] = [
    {
        id: 'S-1',
        sourceType: '생성형',
        category: '탐사',
        title: '달 남극의 영구음영지역, 생명체 흔적 찾기',
        summary: '달 남극의 영구음영지역(PSR)은 수십 억 년 동안 햇빛이 닿지 않아 태양계 초기 역사를 간직하고 있습니다.',
        date: '2025.12.20',
        source: 'Lunar Times',
        publishDate: '2025. 12. 20',
        imageUrl: 'https://images.unsplash.com/photo-1506443432602-ac2fcd6f54e0?q=80&w=300&auto=format&fit=crop',
        body: ['달 남극의 영구음영지역(PSR)은 수십 억 년 동안 햇빛이 닿지 않아 태양계 초기 역사를 간직하고 있습니다. 이곳에서 생명체의 흔적을 찾기 위한 탐사가 시작됩니다.'],
        location: { name: '달 남극', lat: -89.5, lng: 0 },
    },
    {
        id: 'S-2',
        sourceType: '생성형',
        category: '분석',
        title: '우주 부동산: 달 토지 소유권의 법적 쟁점',
        summary: '민간 우주 기업들의 달 진출이 가속화되면서 달 토지 소유권에 대한 국제법적 논쟁이 뜨거워지고 있습니다.',
        date: '2025.11.15',
        source: 'Space Law Review',
        publishDate: '2025. 11. 15',
        imageUrl: 'https://images.unsplash.com/photo-1541873676-a18131494184?q=80&w=300&auto=format&fit=crop',
        body: ['민간 우주 기업들의 달 진출이 가속화되면서 달 토지 소유권에 대한 국제법적 논쟁이 뜨거워지고 있습니다.'],
    },
    {
        id: 'S-3',
        sourceType: '생성형',
        category: '기술',
        title: '테라포밍의 첫걸음: 월면 기지 건설 기술',
        summary: '달 표면의 가혹한 환경을 극복하고 인간이 거주할 수 있는 기지를 건설하기 위한 첨단 기술들이 개발되고 있습니다.',
        date: '2025.10.05',
        source: 'Space Tech Weekly',
        publishDate: '2025. 10. 05',
        imageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?q=80&w=300&auto=format&fit=crop',
        body: ['달 표면의 가혹한 환경을 극복하고 인간이 거주할 수 있는 기지를 건설하기 위한 첨단 기술들이 개발되고 있습니다.'],
    },
];

export const COSMOS_NEWS_DATA: NewsItem[] = [
    {
        id: 'C-1',
        sourceType: '코스모스',
        category: '과학',
        title: '자기장 거의없는 달에 \'자석돌\'? 40억년전 소행성 충돌 흔적!',
        summary: 'MIT 연구팀이 약 40억년 전 거대한 소행성 충돌이 달의 약한 자기장을 일시적으로 강화해 암석에 자기 각인을 남겼을 가능성을 제시했다.',
        date: '2025.05.26',
        source: '코스모스 타임즈',
        publishDate: '2025. 05. 26',
        imageUrl: 'https://www.cosmostimes.net/data/photos/20250522/art_17482207380738_e5071b.jpg',
        originalUrl: 'https://cosmostimes.net/news/article.html?no=25565',
        body: [
            '현재 자기장이 거의 없는 달에서 강하게 자화된 암석이 발견된 것은 수십 년간 과학자들을 의아하게 만들었다.',
            'MIT 연구팀의 슈퍼컴퓨터 시뮬레이션 결과, 소행성 충돌로 생성된 플라스마 구름이 달을 감싸며 자기장을 최대 180마이크로테슬라까지 증폭시켰다.',
            '연구팀은 임브리움 분지와 같은 대형 충돌 지형이 달의 자기 이상 현상과 밀접한 연관이 있음을 확인했다.',
        ],
    },
    {
        id: 'C-2',
        sourceType: '코스모스',
        category: '국제',
        title: '노르웨이 서명, 아르테미스 협정 55개국 동참',
        summary: '노르웨이가 아르테미스 협정에 서명하며 55개국이 동참하는 대형 국제협정이 됐다.',
        date: '2025.05.16',
        source: '코스모스 타임즈',
        publishDate: '2025. 05. 16',
        imageUrl: 'https://www.cosmostimes.net/data/photos/20250520/art_17473592630584_15c5eb.jpg',
        originalUrl: 'https://cosmostimes.net/news/article.html?no=25528',
        body: [
            '노르웨이가 NASA가 주도하는 아르테미스 협정에 서명했다. 이로써 55개국이 동참하는 대형 국제협정이 됐다.',
            '아르테미스 협정은 2020년 10월 미국을 비롯한 7개 국가들과 함께 설립됐으며, 평화적이고 협력적인 우주 활동을 촉진하는 것을 목표로 한다.',
        ],
    },
    {
        id: 'C-3',
        sourceType: '코스모스',
        category: '탐사',
        title: '내년초 달 비행할 유인우주선, SLS 2단 로켓 조립 성공!',
        summary: '아르테미스 2호 미션을 위한 SLS 우주선의 2단 부위 조립이 완료됐다. 내년초 달 유인비행 준비가 착착 진행 중이다.',
        date: '2025.05.06',
        source: '코스모스 타임즈',
        publishDate: '2025. 05. 06',
        imageUrl: 'https://www.cosmostimes.net/data/photos/20250519/art_17464946529518_47025f.jpg',
        originalUrl: 'https://cosmostimes.net/news/article.html?no=25482',
        body: [
            '거대한 SLS 로켓은 NASA 우주선 조립건물 내부에서 계속 세팅되고 있는 중이다.',
            '이 SLS 로켓은 4명의 우주비행사가 탑승하고 아르테미스 2호 미션을 수행하게 된다.',
            '아르테미스 2호는 2026년 초에 발사될 예정이다.',
        ],
    },
    {
        id: 'C-4',
        sourceType: '코스모스',
        category: '탐사',
        title: '미 유인 달탐사에 K-위성 탑재! 아르테미스 2호에 실려 달로~',
        summary: '한국이 개발하는 우주방사선 측정용 큐브위성이 아르테미스 2호에 탑재되어 달을 향해 발사된다.',
        date: '2025.05.02',
        source: '코스모스 타임즈',
        publishDate: '2025. 05. 02',
        imageUrl: 'https://www.cosmostimes.net/data/photos/20250518/art_17461756671834_c80c5b.jpg',
        originalUrl: 'https://cosmostimes.net/news/article.html?no=25472',
        body: [
            '우리나라가 개발하는 우주방사선 측정용 큐브위성 K-라드큐브가 아르테미스 2호에 탑재될 전망이다.',
            'K-라드큐브는 지구와 달 여정 동안의 우주방사선 환경을 분석하고, 유인 우주비행사의 방사선 방호 연구를 수행할 수 있도록 설계됐다.',
        ],
    },
    {
        id: 'C-5',
        sourceType: '코스모스',
        category: '과학',
        title: '태양풍+레골리스=물! 달의 물 기원 확인한 새 연구',
        summary: 'NASA 연구팀이 태양풍이 달 표면에 충돌하면서 물 분자를 생성할 수 있다는 이론을 실험실 시뮬레이션으로 입증했다.',
        date: '2025.04.25',
        source: '코스모스 타임즈',
        publishDate: '2025. 04. 25',
        imageUrl: 'https://www.cosmostimes.net/data/photos/20250417/art_17455637233736_787439.jpg',
        originalUrl: 'https://cosmostimes.net/news/article.html?no=25450',
        body: [
            '태양에서 방출되는 전하 입자, 즉 태양풍이 달 표면에 충돌하면서 물 분자를 생성할 수 있다는 이론이 입증됐다.',
            'NASA 고다드우주비행센터 연구팀은 아폴로 17호의 달 먼지를 사용해 약 8만 년의 달 노출을 시뮬레이션한 실험을 진행했다.',
        ],
    },
    {
        id: 'C-6',
        sourceType: '코스모스',
        category: '과학',
        title: '달의 앞면, 뒷면보다 더 촉촉!',
        summary: '중국 창어 6호가 가져온 달 뒷면 토양 분석 결과, 달의 뒷면이 앞면보다 더 건조하다는 사실이 처음 확인됐다.',
        date: '2025.04.10',
        source: '코스모스 타임즈',
        publishDate: '2025. 04. 10',
        imageUrl: 'https://www.cosmostimes.net/data/photos/20250415/art_17442702839557_5e7337.jpg',
        originalUrl: 'https://cosmostimes.net/news/article.html?no=25387',
        body: [
            '중국과학원 연구팀은 창어 6호가 보낸 달 뒷면 토양의 수분 함량이 g당 1.55㎍에 불과해 앞면(g당 1~200㎍)보다 적다는 사실을 확인했다.',
            '달의 앞뒷면 수분 차이는 대형 소행성 충돌이나 두 반구 간 수분의 수직적 분포 차이로 설명된다.',
        ],
    },
    {
        id: 'C-7',
        sourceType: '코스모스',
        category: '기술',
        title: '"달에서 달먼지 제거 실험 성공" NASA, 우주탐사 위험 제거',
        summary: 'NASA의 전자기 먼지 차폐체(EDS)가 달 표면에서 레골리스를 성공적으로 제거하는 능력을 입증했다.',
        date: '2025.04.07',
        source: '코스모스 타임즈',
        publishDate: '2025. 04. 07',
        imageUrl: 'https://www.cosmostimes.net/data/photos/20250415/art_17440219736494_d901f9.jpg',
        originalUrl: 'https://cosmostimes.net/news/article.html?no=25370',
        body: [
            'NASA의 EDS 기술은 전기역학적 힘을 사용하여 표면에서 달의 먼지를 들어 올리고 제거한다.',
            '이 실험 성과는 열 라디에이터, 태양열 패널, 카메라 렌즈는 물론 우주복까지 적용 가능하다.',
        ],
    },
    {
        id: 'C-8',
        sourceType: '코스모스',
        category: '탐사',
        title: '보라, 달의 황홀한 일몰! \'블루 고스트\'의 마지막 선물',
        summary: '달 착륙선 블루고스트가 달의 일몰 영상을 지구로 전송했다. 달에서 본 일몰, 환상적인 장면이 공개됐다.',
        date: '2025.03.21',
        source: '코스모스 타임즈',
        publishDate: '2025. 03. 21',
        imageUrl: 'https://www.cosmostimes.net/data/photos/20250312/art_17425201235415_dfa37a.jpg',
        originalUrl: 'https://cosmostimes.net/news/article.html?no=25312',
        body: [
            '블루 고스트가 보내온 달의 아름다운 일몰 광경은, 서쪽에서 지는 해 위로 지구와 금성이 등장해 반짝이고 태양이 지면서 달빛이 퍼지는 모습을 보여준다.',
            'NASA의 조엘 케언스는 "해가 달 지평선에서 어둠 속으로 사라지는 모습을 담은 최초의 고화질 사진"이라고 밝혔다.',
        ],
    },
    {
        id: 'C-9',
        sourceType: '코스모스',
        category: '탐사',
        title: '"굿바이, 블루 고스트!" 달 표면의 유령, 임무 종료!',
        summary: '민간 우주선 블루 고스트가 예정된 모든 임무를 완수하고 가동을 종료했다. 14일간의 달 탐사 미션을 성공적으로 완료.',
        date: '2025.03.18',
        source: '코스모스 타임즈',
        publishDate: '2025. 03. 18',
        imageUrl: 'https://www.cosmostimes.net/data/photos/20250312/art_17422594679621_b7a833.jpg',
        originalUrl: 'https://cosmostimes.net/news/article.html?no=25296',
        body: [
            '블루 고스트는 3월 2일 마레 크리시움에 착륙한 뒤 346시간 동안 작동했으며, 달의 밤 이후에도 약 5시간 더 작동한 뒤 수명을 다했다.',
            '파이어플라이의 한국계 CEO 제이슨 킴은 "블루 고스트가 처음으로 달에서 GPS 신호를 추적하는 것부터 달 표면 깊숙이 로봇으로 시추하는 것까지 시연했다"고 밝혔다.',
        ],
    },
    {
        id: 'C-10',
        sourceType: '코스모스',
        category: '탐사',
        title: '"달의 먼지 뚫고 안착했다" 블루 고스트 달 착륙 동영상 공개',
        summary: '파이어플라이 에어로스페이스가 블루 고스트의 역사적인 달 착륙 동영상을 공개했다.',
        date: '2025.03.05',
        source: '코스모스 타임즈',
        publishDate: '2025. 03. 05',
        imageUrl: 'https://www.cosmostimes.net/data/photos/20250310/art_1741142115032_eae5f0.png',
        originalUrl: 'https://cosmostimes.net/news/article.html?no=25243',
        body: [
            '멀리 보이던 달의 표면이 점점 가까워지고 울퉁불퉁 크레이터들이 생생해질 때 블루 고스트의 그림자가 달 표면에 생겨났다.',
            '블루 고스트는 마레 크리시움의 몽스 라트레유 근처에 착륙했다.',
        ],
    },
    {
        id: 'C-11',
        sourceType: '코스모스',
        category: '기술',
        title: '"달에 GPS 위성 시스템 추진" 미·일·유럽, 2030년대 구축',
        summary: '미국, 일본, 유럽이 달 주변을 도는 GPS 위성 시스템을 2030년대 중반까지 구축할 계획이다.',
        date: '2025.02.20',
        source: '코스모스 타임즈',
        publishDate: '2025. 02. 20',
        imageUrl: 'https://www.cosmostimes.net/data/photos/20250208/art_17400428132765_b0cd18.jpg',
        originalUrl: 'https://cosmostimes.net/news/article.html?no=25199',
        body: [
            'NASA는 2027년까지 인공위성 2기 이상, ESA는 1기 이상, JAXA는 이르면 2028년 1기를 달 상공에 보낼 계획이다.',
            '위성 4기 체제로 기술 실증 후 2030년대 중반까지 8기 체제로 늘려 고정밀 위치 측정을 실현한다는 구상이다.',
        ],
    },
    {
        id: 'C-12',
        sourceType: '코스모스',
        category: '탐사',
        title: '다누리, 2년 더 달 탐사! 수명 연장... 고도 낮춰 정밀관측',
        summary: '한국형 달 탐사선 다누리의 임무 기간이 2027년 말까지 2년 더 늘어난다.',
        date: '2025.02.11',
        source: '코스모스 타임즈',
        publishDate: '2025. 02. 11',
        imageUrl: 'https://www.cosmostimes.net/data/photos/20250207/art_17391836584301_ecfdfa.jpg',
        originalUrl: 'https://cosmostimes.net/news/article.html?no=25155',
        body: [
            '2022년 발사된 다누리는 연료를 많이 아껴 당초 임무 기간보다 연장되었으며, 이번 결정을 통해 2027년까지 수명이 더 늘어났다.',
            '고도를 100km에서 60km로 낮춰 7개월간 운영하며, 이후 동결궤도로 진입해 장기 운영한다.',
        ],
    },
    {
        id: 'C-13',
        sourceType: '코스모스',
        category: '역사',
        title: '닐 암스트롱 손편지 경매 나온다',
        summary: '아폴로 11호와 관련된 닐 암스트롱의 자필 편지와 미션 패치 디자인 등이 경매에 나온다.',
        date: '2025.02.10',
        source: '코스모스 타임즈',
        publishDate: '2025. 02. 10',
        imageUrl: 'https://www.cosmostimes.net/data/photos/20250207/art_17391538713699_cae7ce.jpg',
        originalUrl: 'https://cosmostimes.net/news/article.html?no=25149',
        body: [
            '2월 27일 로스앤젤레스에서 열리는 골드버그 코인&컬렉터블 경매에 암스트롱의 자필 편지와 앰블럼 아트 등이 출품된다.',
            '이번 경매에는 아폴로 8, 9, 10, 11, 12, 13호 미션 패치에 대한 콘셉트가 포함되어 있다.',
        ],
    },
    {
        id: 'C-14',
        sourceType: '코스모스',
        category: '탐사',
        title: '달 착륙선 2개 싣고 팰컨9 발사! "달에서 봐요"',
        summary: '미국과 일본의 민간 달 착륙선 2개를 실은 스페이스X 팰컨9 로켓이 성공적으로 발사됐다.',
        date: '2025.01.15',
        source: '코스모스 타임즈',
        publishDate: '2025. 01. 15',
        imageUrl: 'https://www.cosmostimes.net/data/photos/20250103/art_1736920288081_b0152e.jpg',
        originalUrl: 'https://cosmostimes.net/news/article.html?no=25057',
        body: [
            '파이어플라이 에어로스페이스의 블루 고스트와 아이스페이스의 레질리언스가 함께 발사됐다.',
            '블루 고스트는 3월초 마레 크리시움에, 레질리언스는 5월말 마레 프리고리스에 각각 착륙을 시도한다.',
        ],
    },
    {
        id: 'C-15',
        sourceType: '코스모스',
        category: '과학',
        title: '달의 나이 43.5억 년 맞나? 새 연구 "약 45억살 됐다"',
        summary: '중국 창어 6호 임무로 수집된 월석 분석 결과, 달이 기존 추정보다 1억 년 더 오래되었을 수 있다는 연구가 나왔다.',
        date: '2024.12.19',
        source: '코스모스 타임즈',
        publishDate: '2024. 12. 19',
        imageUrl: 'https://www.cosmostimes.net/data/photos/20241251/art_17345931517954_1050f5.jpg',
        originalUrl: 'https://cosmostimes.net/news/article.html?no=24953',
        body: [
            '연구팀의 모델링에 따르면, 달은 가열과 냉각의 시기를 거쳐 표면이 녹아내렸고 더 오래된 달의 특징이 숨겨져 있을 수 있다.',
            '태양계 초기에는 거대한 우주 충돌이 흔했으며, 연구팀의 컴퓨터 모델에 따르면 달은 태양계 형성 이후 약 8000만 년 뒤에 형성됐다.',
        ],
    },
];
